@category = headphones

# @name getProductsByCategory
GET http://localhost:3333/products/category/{{category}}

###

@productId = {{getProductsByCategory.response.body.$[0].productId}}

# @name getProductById
GET http://localhost:3333/products/{{productId}}

###

# @name addProduct
POST http://localhost:3333/products
Content-Type: application/json

{
  "name": "product name 2",
  "description": "product description",
  "price": 26.00,
  "categories": ["d61ccf6d-b8f7-48a9-ba0e-a15b0050bfae"],
  "imageUrl": "https://localhost:3333",
  "quantity": 12,
  "discountId": "e63d5eaa-dba7-4b5f-a4bd-3297a371a71c"
}

###

# @name releaseProduct
POST http://localhost:3333/products/4cac7bb2-6cb5-43e6-bfee-1f0ab4e3ae92/release

###

# @name updateProduct
PUT http://localhost:3333/products/4cac7bb2-6cb5-43e6-bfee-1f0ab4e3ae92
Content-Type: application/json

{
  "name": "product name 2 updated",
  "description": "product description updated",
  "summary": "product description",
  "price": 36.00,
  "categories": ["d61ccf6d-b8f7-48a9-ba0e-a15b0050bfae"],
  "imageUrl": "https://localhost:3333",
  "quantity": 20,
  "discountId": "e63d5eaa-dba7-4b5f-a4bd-3297a371a71c"
}

###

# @name listProducts
GET http://localhost:3333/products