@category = headphones

# @name getProductsByCategory
GET http://localhost:3333/api/category/{{category}}/products

###

@productId = {{getProductsByCategory.response.body.products.$[0].productId}}

# @name getProductById
GET http://localhost:3333/api/products/{{productId}}

###

# @name addProduct
POST http://localhost:3333/api/products
Content-Type: application/json

{
  "name": "product name 2",
  "description": "product description",
  "price": 26.00,
  "categories": ["d61ccf6d-b8f7-48a9-ba0e-a15b0050bfae"],
  "imageUrl": "https://localhost:3333",
  "quantity": 12,
  "discountId": "e63d5eaa-dba7-4b5f-a4bd-3297a371a71c"
}

###

# @name releaseProduct
POST http://localhost:3333/api/products/4cac7bb2-6cb5-43e6-bfee-1f0ab4e3ae92/release

###

# @name createRating
POST http://localhost:3333/api/products/{{productId}}/rating
Content-Type: application/json
Authorization: Bearer ce4702fb-ae6e-4b5f-b502-916230d0654a

{
  "score": 4,
  "description": "cool stuff"
}

###

# @name updateProduct
PUT http://localhost:3333/api/products/4cac7bb2-6cb5-43e6-bfee-1f0ab4e3ae92
Content-Type: application/json

{
  "name": "product name 2 updated",
  "description": "product description updated",
  "summary": "product description",
  "price": 36.00,
  "categories": ["d61ccf6d-b8f7-48a9-ba0e-a15b0050bfae"],
  "imageUrl": "https://localhost:3333",
  "quantity": 20,
  "discountId": "e63d5eaa-dba7-4b5f-a4bd-3297a371a71c"
}

###

# @name listProducts
GET http://localhost:3333/api/products

###

# @name listCategories
GET http://localhost:3333/api/category

###

# @name createCategory
POST http://localhost:3333/api/category
Content-Type: application/json

{
  "name": "Video Games"
}

###

@categoryId = {{createCategory.response.body.categoryId}}

# @name getCategorybyId
GET http://localhost:3333/api/category/4a7a41d1-879e-43ba-9e1b-6eab6e1b446b

###

# @name updateCategory
PUT http://localhost:3333/api/category/{{categoryId}}
Content-Type: application/json

{
  "name": "Cosmetic 2"
}