version: '3'

services:
  postgres:
    image: postgres:15.5-alpine
    ports:
      - 5433:5432
    volumes:
      - .docker/.pgdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=storesyDB

  redis:
    image: bitnami/redis:latest
    environment:
      - REDIS_PASSWORD=123
    ports:
      - 6379:6379
    volumes:
      - .docker/.redisdata:/bitnami/redis/data
